[project]
name = 'Recyclix'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Recyclix]
path = 'contracts/Recyclix.clar'
clarity_version = 3
epoch = 3.1

[contracts.RecyclingLocationTracker]
path = 'contracts/RecyclingLocationTracker.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
